language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "gvq/Y+L5rQ+4GI1TudNkvTWdcWYR2kwDl3DNcQQ7SV8Pm7DBlQYCvSEahOtyThfGy4dEc4mCG2H6uRgOAY8Ox8GwCytbZKywdUFMFN0oUiLA11zJFK02FH2JEiz1BxtDq7xoePZ09uLHOXI/qzfevptiWA4H3tLPpk+tqo/6JAY="
    on:
      tags: true
      all_branches: true
